[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
exclude = '''
/(
    \.git
  | \.tox
  | .gitignore
  | environment.yml
  | environment_dev.yml
  | LICENSE
  | pylintrc
  | README.md
  | setup.cfg
)/
'''

[tool.isort]
profile = "black"