[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pte"
version = "0.1.0"
description = "PTE is an open-source software package for working with electrophysiological data"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE.txt"}
keywords = ["eeg", "ieeg", "dbs", "adbs", "ecog", "lfp"]
authors = [
  {name = "Richard Köhler"}
]
maintainers = [
  {name = "Richard Köhler"}
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.9",
  "Topic :: Software Development :: Libraries :: Python Modules"
]

dependencies = [
  "joblib",
  "matplotlib",
  "mne",
  "mne-bids",
  "numba",
  "numpy",
  "pandas",
  "pip",
  "plotly",
  "scikit-image",
  "scipy"
]

[project.optional-dependencies]
test = [
  "pylint",
  "pytest",
]
style = [
  "black",
  "isort"
]

[project.urls]
repository = "https://github.com/richardkoehler/pte"
changelog = "https://github.com/richardkoehler/pte/blob/main/doc/CHANGELOG.md"
bugtracker = "https://github.com/richardkoehler/pte/issues"

[tool.black]
line-length = 79
target-version = ['py39']
exclude = '''
/(
    \.git
  | \.tox
  | .gitignore
  | environment.yml
  | environment_dev.yml
  | LICENSE.txt
  | pylintrc
  | README.md
  | setup.cfg
)/
'''

[tool.isort]
profile = "black"
line_length = 79
py_version = 39
src_paths = ["pte"]
