name: lint_and_format

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
  
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Lint the code with pylint
      run: |
        pip install pylint
        pylint --rcfile pylintrc $(git ls-files '*.py')

    - name: Lint with isort
      run: |
        pip install isort
        isort $(git ls-files '*.py')

    - name: Format with black
      run: |
        pip install black
        black . --verbose

