name: lint_and_format

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
  
on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'doc/**'
      - '*.md'
      - '*.rst'
      - '*.txt'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'doc/**'
      - '*.md'
      - '*.rst'
      - '*.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Pylint check
      run: |
        pip install pylint
        pylint --rcfile pylintrc $(git ls-files '*.py')

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
